version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"  # Перенаправление порта 80 контейнера на порт 8080 хоста
    volumes:
      - .:/var/www/html
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/www/html/firebase-key.json
